version: "3.4"

services:
    php:
        build:
            context: ./docker
        command: ["tail", "-f", "/dev/null"]
        user: '1000'
        environment:
            - PHP_IDE_CONFIG=serverName=guuzen-resource-composer
            - COMPOSER_HOME=/app/docker/php/composer_home
        volumes:
            - ./:/app

